main: me.Siup.TP.Main
name: Teleport
version: 3.0
author: Siup

commands:
   nazwij:
      description: Uzycie /nazwij <nickname>
   ok:
      description: Uzycie /pozwolenie <sprawdz|zmien>
   nie:
      description: penis
 